### ISSUE TITLE
No logging of Deploy Logs

### ISSUE THREAD

**Issue by Skowt** [half0wl/railway-chord#16]
I've got a Python app that's deployed from a GitHub repo. If I look at Railway I can see that there's no tab for 'Logs' but I can see the active logs in 'Deploy Logs' when I click into the latest deployment. 

I suspect that this is why I don't see logs for my service in LogTail? I do get logs from my Redis service in the same project though but nothing else.

The logs view for my app:
<img width="1293" alt="Screenshot 2023-05-01 at 9 27 56 PM" src="https://user-images.githubusercontent.com/4960236/235516042-f068c599-3207-46d7-9819-3e66b4a732a1.png">

**Comment by half0wl** [comment]
Deploy logs are the logs you want and should see in Logtail.

Can you paste the deploy logs of railway-chord here?

**Comment by Skowt** [comment]
So Railway looks like it's looping it's own Deploy logs indefinitely. Maybe I've got it setup incorrectly with `stdout=True`? Here are the initial logs before it starts looping:

```
⚡ railway-chord is starting!
⚙️  Using Vector binary: /app/vector/bin/vector
✅ Vector started
✅ Enabled sinks:
- stdout
- logtail
⚙️  Using Railway HTTP endpoint: https://backboard.railway.app/graphql/v2
⚙️  Using Railway WS endpoint: wss://backboard.railway.app/graphql/v2
🔄 Refreshing projects!
[process::vector/stdout] >>> ping from railway-chord
>>> ping from railway-chord
[process::vector/stderr] 2023-05-08T07:39:35.647027Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,lapin=info,kube=info"
2023-05-08T07:39:35.648146Z  INFO vector::app: Loading configs. paths=["/tmp/tmp-1-vXXXQ"]
2023-05-08T07:39:35.651984Z  INFO vector::sources::file_descriptors: Capturing stdin.
2023-05-08T07:39:35.688646Z  INFO vector::topology::running: Running healthchecks.
2023-05-08T07:39:35.688760Z  INFO vector::topology::builder: Healthcheck passed.
2023-05-08T07:39:35.688788Z  INFO vector::topology::builder: Healthcheck passed.
2023-05-08T07:39:35.688844Z  INFO vector: Vector has started. debug="false" version="0.29.1" arch="x86_64" revision="74ae15e 2023-04-20 14:50:42.739094536"
2023-05-08T07:39:35.688868Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
✅ Enabling for:
> projectId=XXXX
- deployment=XXX.up.railway.app, deploymentId=XXX
- plugin=redis, pluginId=XXX, env=production
```

It then repeats these same logs in JSON format (which is what I end up seeing in Logtail) and then repeats them again but with an extra set of timestamps, making me believe that there's a loop happening for this project. Do I need to deploy Railway Vector Log to it's own project so that this loop doesn't occurr 🤔 ?

**Comment by half0wl** [comment]
> `- deployment=XXX.up.railway.app, deploymentId=XXX`

Does this match your expectation of the deployment you expect to see logs for in Logtail?

I'm wondering if the API is returning anything at all; in theory that's the only point-of-failure I can see.

> It then repeats these same logs in JSON format (which is what I end up seeing in Logtail) and then repeats them again but with an extra set of timestamps, making me believe that there's a loop happening for this project. Do I need to deploy Railway Vector Log to it's own project so that this loop doesn't occurr 🤔 ?

Turn off stdout by setting `ENABLE_STDOUT` to `false` in your service environments. 

And yeah, ideally you should have this in a separate independent project, since the goal here is to be able to act as a sink for _all_ projects. I should clarify this behaviour 😅

**Comment by Skowt** [comment]
I see this:

```2023-05-09T13:14:25.470018Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.```

Is this possibly related 🤔 ?

**Comment by Skowt** [comment]
> Do you see your deployment's logs inside the new railway-chord service's deploy logs

Negative! I can watch the logs in its own container but I cannot see them in `chord` 😅 Although Redis logs were working at a point. I wonder if it's because I'm deploying from Repo, so it's not some official app? Maybe it's not supported that way? I'm not sure but I'll keep poking at it as well.

**Comment by Skowt** [comment]
Hold up @half0wl 🙌🏼  I switched to Datadog (from LogTail) and it's now somehow working. I do see some errors in Chord's deploy logs now and then but for the most part, Datadog is showing me logs now. 

I'm not sure what fixed it, if it was an issue with LogTail or moving chord to its own project but something helped :/ Pesky programming issues. Sorry for the headaches man!
